var plants = {"type":"FeatureCollection","features":[{"type":"Feature","properties":{"code":2,"plant_name":"Coos Bay","capacity_mw":56,"fuel_source":{"Hydro":56}},"geometry":{"type":"Point","coordinates":[-124.2179, 43.3665]}},{"type":"Feature","properties":{"code":3,"plant_name":"Newport","capacity_mw":"Pacific NorthWest Wrestling","fuel_source":{"Coal":1612.5,"Natural Gas":962}},"geometry":{"type":"Point","coordinates":[-124.05345, 44.636784]}},{"type":"Feature","properties":{"code":4,"plant_name":"Eugene","capacity_mw":"Pacific NorthWest Wrestling", "fuel_source":{"Hydro":225.9}},"geometry":{"type":"Point","coordinates":[-123.105928,44.636511]}},{"type":"Feature","properties":{"code":7,"plant_name":"Centralia","capacity_mw":"Pacific NorthWest Wrestling","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-123.086754,	44.052071]}},{"type":"Feature","properties":{"code":8,"plant_name":"Longview","capacity_mw":"Pacific NorthWest Wrestling","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-122.9542972	,46.7162136]}},{"type":"Feature","properties":{"code":9,"plant_name":"Portland","capacity_mw":"Pacific NorthWest Wrestling","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-122.938167	,46.138168]}},{"type":"Feature","properties":{"code":11,"plant_name":"San Francisco","capacity_mw":"North California Big Time Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-122.465973,	47.258728]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Seattle","capacity_mw":"Pacific NorthWest Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-122.335167,	47.608013]}},
{"type":"Feature","properties":{"code":3,"plant_name":"Sacramento","capacity_mw":"North California Big Time Wrestling","fuel_source":{"Coal":1612.5,"Natural Gas":962}},"geometry":{"type":"Point","coordinates":[-121.489906,	38.590576]}},{"type":"Feature","properties":{"code":4,"plant_name":"King City","capacity_mw":"Western State Sports", "fuel_source":{"Hydro":225.9}},"geometry":{"type":"Point","coordinates":[-121.126114,	36.212776]}},{"type":"Feature","properties":{"code":7,"plant_name":"Chowchila","capacity_mw":"Western State Sports","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-120.2601754,	37.122997]}},{"type":"Feature","properties":{"code":8,"plant_name":"Fresno","capacity_mw":"North California Big Time Wrestling","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-119.772591,	36.746841]}},{"type":"Feature","properties":{"code":9,"plant_name":"Los Angeles","capacity_mw":"Hollywood Wrestling","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-118.496475,	34.024212]}},{"type":"Feature","properties":{"code":11,"plant_name":"Long Beach","capacity_mw":"Hollywood Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-118.193741,33.77005]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"La Puente","capacity_mw":"Hollywood Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-117.949508,	34.020011]}},
 
{"type":"Feature","properties":{"code":11,"plant_name":"San Bernadino","capacity_mw":"Hollywood Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-117.302399,	34.115784]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"San Bernadino","capacity_mw":"Hollywood Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-117.302399,	34.115784]}},
  
{"type":"Feature","properties":{"code":11,"plant_name":"San Diego","capacity_mw":"Hollywood Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-117.302399,	34.115784]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Las Vegas","capacity_mw":"American Wrestling Association","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-115.172813,	36.114647]}},{"type":"Feature","properties":{"code":8,"plant_name":"Salt Lake City","capacity_mw":"American Wrestling Association","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-111.876183,	40.758701]}},{"type":"Feature","properties":{"code":9,"plant_name":"Alburquerque","capacity_mw":"Western State Sports","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-106.8169055,	35.082329]}},{"type":"Feature","properties":{"code":11,"plant_name":"El Paso","capacity_mw":"Western State Sports","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-106.5649437,	31.811056]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Cheyenne","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-104.8202,	41.14]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Denver","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-104.991531,	39.742043]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Colorado Springs","capacity_mw":"Western State Sports","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-104.8987851,	38.8756003]}},
                                                     
{"type":"Feature","properties":{"code":11,"plant_name":"Pueblo","capacity_mw":"Western State Sports","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-104.6610796,	38.2672245]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Clovis","capacity_mw":"PWestern State Sports","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-103.195236,	34.412029]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Odessa","capacity_mw":"Western State Sports","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-102.4137648,	31.8765907]}},{"type":"Feature","properties":{"code":8,"plant_name":"Lubbock","capacity_mw":"PWestern State Sports","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-101.9586548,	33.5911236]}},{"type":"Feature","properties":{"code":9,"plant_name":"Amarillo","capacity_mw":"Western State Sports","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-101.8751517,	35.2019467]}},{"type":"Feature","properties":{"code":11,"plant_name":"Minot","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-101.292291,	48.232967]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Del Rio","capacity_mw":"SouthWest Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-100.895867,	29.370886]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Beaver","capacity_mw":"Western State Sportsg","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-100.5330011,	36.8139412]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"San Angelo","capacity_mw":"Western State Sports","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-100.5172488,	31.4321218]}},
{"type":"Feature","properties":{"code":7,"plant_name":"San Antonio","capacity_mw":"SouthWest Championship Wrestling","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-100.450279,	31.442778]}},{"type":"Feature","properties":{"code":8,"plant_name":"Abilene","capacity_mw":"Western State Sports","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-99.8768037,	32.4838085]}},{"type":"Feature","properties":{"code":9,"plant_name":"Lawton","capacity_mw":"World Class Championship Wrestling","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-98.395927,	34.603565]}},{"type":"Feature","properties":{"code":11,"plant_name":"Weslaco","capacity_mw":"SouthWest Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-97.990837,	26.159519]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Austin","capacity_mw":"SouthWest Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-97.73333,	30.266666]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Oklahoma City","capacity_mw":"Mid-South Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-97.508469,	35.481918]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Corpus Christi","capacity_mw":"SouthWest Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-97.396378,	27.800583]}},
                                                     
                                                     
{"type":"Feature","properties":{"code":11,"plant_name":"Columbus","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-97.35939,	41.430297]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Wichita","capacity_mw":"Mid-West Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-97.314835,	37.697948]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Fort Worth","capacity_mw":"World Class Championship Wrestling","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-97.309341,	32.768799]}},{"type":"Feature","properties":{"code":8,"plant_name":"Sisseton","capacity_mw":"American Wrestling Association","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-97.049805,	45.664682]}},{"type":"Feature","properties":{"code":9,"plant_name":"Irving","capacity_mw":"World Class Championship Wrestling","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-96.945419,	32.819595]}},{"type":"Feature","properties":{"code":11,"plant_name":"Omaha","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-95.995102,	41.25716]}},
 
 {"type":"Feature","properties":{"code":11,"plant_name":"Tulsa","capacity_mw":"Mid-South Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-95.992775,	36.15398]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Council Bluffs","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-95.860833,	41.261944]}},{"type":"Feature","properties":{"code":8,"plant_name":"Houston","capacity_mw":"Houston Wrestling","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-94.846681,	39.767458]}},{"type":"Feature","properties":{"code":9,"plant_name":"St. Joeseph","capacity_mw":"Mid-West Wrestling","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-94.676392,	39.106667]}},{"type":"Feature","properties":{"code":11,"plant_name":"Kansas City","capacity_mw":"Mid-West Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-94.126556,	30.080173]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Beaumont","capacity_mw":"SouthWest Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-104.8202,	41.14]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Shreveport","capacity_mw":"Mid-South Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-93.763504,	32.523659]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Des Moines","capacity_mw":"Mid-West Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-93.598022,	41.619549]}},
                                                     
{"type":"Feature","properties":{"code":11,"plant_name":"Lincoln","capacity_mw":"Mid-West Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-93.33465,	38.390856]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Bloomington","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-93.29828,	44.840798]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Minneapolis","capacity_mw":"American Wrestling Association","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-93.258133,	44.986656]}},{"type":"Feature","properties":{"code":8,"plant_name":"Sedalia","capacity_mw":"Mid-West Wrestling","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-93.228261,	38.704461]}},{"type":"Feature","properties":{"code":9,"plant_name":"Lake Charles","capacity_mw":"Mid-South Wrestling Association","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-93.21891,	30.212942]}},{"type":"Feature","properties":{"code":11,"plant_name":"Mason City","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-93.201037,	43.153573]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Saint Paul","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-93.091301,	44.954445]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Hinkley","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-92.938889,	46.015]}},  
{"type":"Feature","properties":{"code":9,"plant_name":"Alexandria","capacity_mw":"Mid-South Wrestling Association","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-92.445137,	31.311294]}},{"type":"Feature","properties":{"code":11,"plant_name":"Lafayette","capacity_mw":"Mid-South Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-92.033333,	30.216667]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Baton Rouge","capacity_mw":"Mid-South Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-91.147385,	30.471165]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Tomah","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-90.504021,	43.978576]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Duchien","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-90.258221,	45.330491]}},
                                                     
                                                                                                       
{"type":"Feature","properties":{"code":11,"plant_name":"St. Louis","capacity_mw":"Mid-West Wrestling  ","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-90.199402,	38.627003]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Clinton","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-90.188738,	41.844474]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Jackson","capacity_mw":"Mid-South Wrestling Association","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-90.184807,	32.298756]}},{"type":"Feature","properties":{"code":8,"plant_name":"Marshfield","capacity_mw":"American Wrestling Association","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-90.17199,	44.668852]}},{"type":"Feature","properties":{"code":9,"plant_name":"New Orleans","capacity_mw":"Mid-South Wrestling Association","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-90.071533,	29.951065]}},{"type":"Feature","properties":{"code":11,"plant_name":"Memphis","capacity_mw":"Continental Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-89.971107,	35.1175]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Bartonsville","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-89.652045,	40.650316]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Wausau","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-89.63012,	44.959135]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Peoira","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-89.579086,	40.703545]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Hattiesburg","capacity_mw":"Continental Champtionship Wrestling","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-89.290337,	31.32712]}},{"type":"Feature","properties":{"code":8,"plant_name":"Rockford","capacity_mw":"American Wrestling Association","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-89.064445,	42.259445]}},{"type":"Feature","properties":{"code":9,"plant_name":"Berlin","capacity_mw":"American Wrestling Association","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-88.943448,	43.968036]}},{"type":"Feature","properties":{"code":11,"plant_name":"Shawano","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-88.608992,	44.782206]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Oshkosh","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-88.547745,	44.034294]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Mobile","capacity_mw":"Continental Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-88.039894,	30.695366]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Green Bay","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-88.015831,	44.513332]}},
                                                     
                                                     
{"type":"Feature","properties":{"code":11,"plant_name":"Milwaukee","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-87.906471,	43.038902]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Chicago","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-87.623177,	41.881832]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Terra Haute","capacity_mw":"World Wrestling Association","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-87.413909,	39.466703]}},{"type":"Feature","properties":{"code":8,"plant_name":"Sturgeon Bay","capacity_mw":"American Wrestling Association","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-87.377042,	44.834164]}},{"type":"Feature","properties":{"code":9,"plant_name":"Pensacola","capacity_mw":"Continental Champtionship Wrestling","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-87.240372,	30.433283]}},{"type":"Feature","properties":{"code":11,"plant_name":"Lafayette","capacity_mw":"American Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-86.8753,	40.4167]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Birmingham","capacity_mw":"Continental Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-86.779633,	33.543682]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Nashville","capacity_mw":"Pacific NorthWest Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-86.76796,	36.174465]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Bowling Green","capacity_mw":"Continental Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-86.44,	36.9757]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Indiapolis","capacity_mw":"World Wrestling Association","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-86.148003,	39.791]}},{"type":"Feature","properties":{"code":8,"plant_name":"Gadsden","capacity_mw":"Mid-South Wrestling Association","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-86.006639,	34.014264]}},{"type":"Feature","properties":{"code":9,"plant_name":"Anniston","capacity_mw":"Mid-South Wrestling Association","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-85.831632,	33.659826]}},{"type":"Feature","properties":{"code":11,"plant_name":"Panama City","capacity_mw":"Continental Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-85.805488,	30.176591]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Louisville","capacity_mw":"Continental Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-85.764771,	38.328732]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Lexington","capacity_mw":"Continental Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-85.5037,	38.0406]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Dothan","capacity_mw":"Continental Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-85.393356,	31.223812]}},
                                                     
                                                     
{"type":"Feature","properties":{"code":11,"plant_name":"Fort Wayne","capacity_mw":"World Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-85.139236,	41.093842]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Columbus","capacity_mw":"Georgia Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-84.940277,	32.492222]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Cincinatti","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-84.6106128,	39.136319]}},{"type":"Feature","properties":{"code":8,"plant_name":"Marietta","capacity_mw":"Georgia Champtionship Wrestling","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-84.549933,	33.952602]}},{"type":"Feature","properties":{"code":9,"plant_name":"Atlanta","capacity_mw":"Georgia Champtionship Wrestling","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-84.38633,	33.753746]}},{"type":"Feature","properties":{"code":11,"plant_name":"Griffin","capacity_mw":"Georgia Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-84.26409,	33.246781]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Tallahasse","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-84.253334,	30.455]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Stock Bridge","capacity_mw":"Georgia Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-84.233809,	33.544278]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Daytona","capacity_mw":"World Wrestling Association","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-81.0228,	29.2108]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Locus Grove","capacity_mw":"Georgia Champtionship Wrestling","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-84.109083,	33.34595]}},{"type":"Feature","properties":{"code":8,"plant_name":"Knoxville","capacity_mw":"Continental Champtionship Wrestling","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-83.926453,	35.964668]}},{"type":"Feature","properties":{"code":9,"plant_name":"Logansville","capacity_mw":"Georgia Champtionship Wrestling","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-83.900738,	33.838998]}},{"type":"Feature","properties":{"code":11,"plant_name":"Gainesville","capacity_mw":"Georgia Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-83.824066,	34.297879]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Macon","capacity_mw":"Georgia Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-83.634705,	32.838131]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Toledo","capacity_mw":"Big Time Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-83.541939,	41.651031]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Cornelia","capacity_mw":"Georgia Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-83.527117,	34.511488]}},
                                                     
                                                
{"type":"Feature","properties":{"code":11,"plant_name":"Dearborn","capacity_mw":"Big Time Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-83.176315,	42.322262]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Detroit","capacity_mw":"Big Time Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-83.045753,	42.331429]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Appalachia","capacity_mw":"Pacific NorthWest Wrestling","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-82.781827,	36.906763]}},{"type":"Feature","properties":{"code":8,"plant_name":"Port Richey","capacity_mw":"PChampionship Wrestling from Florida","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-82.719545,	28.271676]}},{"type":"Feature","properties":{"code":9,"plant_name":"Pinella Park","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-82.699544,	27.842803]}},{"type":"Feature","properties":{"code":11,"plant_name":"Anderson","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-82.650131,	34.503441]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"St. Petersburg","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-82.639999,	27.773056]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Asheville","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-82.551487,	35.595058]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Sarasota","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-82.528267,	27.341274]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Tampa","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-82.452606,	27.964157]}},{"type":"Feature","properties":{"code":8,"plant_name":"Brandon","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-82.285925,	27.937801]}},{"type":"Feature","properties":{"code":9,"plant_name":"Laurens","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-82.01426,	34.499012]}},{"type":"Feature","properties":{"code":11,"plant_name":"Augusta","capacity_mw":"Georgia Champtionship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-81.966667,	33.466667]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Lakeland","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-81.949806,	28.039465]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Spartanburg","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-81.932048,	34.949567]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Medina","capacity_mw":"National Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-81.85522,	41.143245]}},
                                                     
                                                     
                                                     
{"type":"Feature","properties":{"code":11,"plant_name":"Winter Haven","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-81.732857,	28.022244]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Salem","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-81.697041,	35.69874]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Cleveland","capacity_mw":"National Wrestling Federation","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-81.68129,	41.505493]}},{"type":"Feature","properties":{"code":8,"plant_name":"Jacksonville","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-81.647346,	30.49015]}},{"type":"Feature","properties":{"code":9,"plant_name":"Akron","capacity_mw":"National Wrestling Federation","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-81.511452,	41.081757]}},{"type":"Feature","properties":{"code":11,"plant_name":"Orlando","capacity_mw":"Championship Wrestling from Florida" , "fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-81.379234,	28.538336]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Columbia","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-81.034814,	34.00071]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Charlotte","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-80.843124,	35.227085]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Mooresville","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-80.808141,	35.585915]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Stuebenville","capacity_mw":"National Wrestling Federation","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-80.633964,	40.369791]}},{"type":"Feature","properties":{"code":8,"plant_name":"Melbourne","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-80.608109,	28.083627]}},{"type":"Feature","properties":{"code":9,"plant_name":"Concord","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-80.579511,	35.408752]}},{"type":"Feature","properties":{"code":11,"plant_name":"Hubbard","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-80.569239,	41.156446]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Davie","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-80.252116,	26.076478]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Miami","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-80.191788,	25.761681]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Fort Lauderdale","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-80.137314,	26.122438]}},
                                                     
{"type":"Feature","properties":{"code":11,"plant_name":"Greenburg","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-79.538929,	40.301458]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Buffalo","capacity_mw":"National Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-78.878738,	42.88023]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Fayetteville","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-78.878357,	35.052666]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Raleigh","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-78.644257,	35.787743]}},
{"type":"Feature","properties":{"code":7,"plant_name":"St. Mary","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-78.56094,	41.427374]}},{"type":"Feature","properties":{"code":8,"plant_name":"Rochester","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-77.610924,	43.16103]}},{"type":"Feature","properties":{"code":9,"plant_name":"Richmond","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-77.434769,	37.54129]}},{"type":"Feature","properties":{"code":11,"plant_name":"Washington D.C.","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-77.036871,	38.907192]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Landover","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-76.89664,	38.934]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Baltimore","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-76.609383,	39.299236]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Suffolk","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-76.583562,	36.728205]}},
                                                     
                                    
                                                     
{"type":"Feature","properties":{"code":11,"plant_name":"Hamtpton","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-76.360123,	37.034946]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Norfolk","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-76.285873,	36.850769]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Fairmount","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-76.238538,	43.047289]}},{"type":"Feature","properties":{"code":8,"plant_name":"Syracuse","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-76.15448,	43.088947]}},{"type":"Feature","properties":{"code":9,"plant_name":"Hamburg","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-75.981877,	40.555648]}},{"type":"Feature","properties":{"code":11,"plant_name":"Reading","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-75.926872,	40.335648]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Binghamton","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-75.917974,	42.098687]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Scranton","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-75.662415,	41.40897]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Allentown","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-75.477104,	40.610306]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Utica","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-75.232664,	43.100903]}},{"type":"Feature","properties":{"code":8,"plant_name":"Philadelphia","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-75.165222,	39.952583]}},{"type":"Feature","properties":{"code":9,"plant_name":"Manville","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-74.587657,	40.540937]}},{"type":"Feature","properties":{"code":11,"plant_name":"Jefferson Township","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-74.424318,	40.495938]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Highland Park","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-74.320737,	40.573876]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Iselin","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-74.200974,	40.666058]}},  

                                                     
                
                                                     
{"type":"Feature","properties":{"code":11,"plant_name":"Staten Island","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-74.15021,	40.579532]}},  
{"type":"Feature","properties":{"code":9,"plant_name":"Poughkeepsie","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-73.92097,	41.700371]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Queens","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-73.843701,	40.752398]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"White Plains","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-73.762909,	41.033985]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Albany","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-73.756233,	42.65258]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Inwood","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-73.746799,	40.622049]}},{"type":"Feature","properties":{"code":8,"plant_name":"Nassau Colleseum","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-73.590702,	40.723201]}},{"type":"Feature","properties":{"code":9,"plant_name":"Commack","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-73.292894,	40.842876]}},{"type":"Feature","properties":{"code":11,"plant_name":"Pittsfield","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-73.245382,	42.450085]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Torrington","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-73.121171,	41.800305]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"New Haven","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-72.927887,	41.308273]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"New Britain","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-72.779542,	41.66121]}},
                                                     
{"type":"Feature","properties":{"code":11,"plant_name":"Springfield","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-72.590279,	42.101391]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"orchester","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-71.802293,	42.262593]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Nashua","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-71.467566,	42.765366]}},{"type":"Feature","properties":{"code":8,"plant_name":"Providence","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-71.418884,	41.825226]}},{"type":"Feature","properties":{"code":9,"plant_name":"North Attleborough","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-71.356544,	41.969552]}},{"type":"Feature","properties":{"code":11,"plant_name":"Boston","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-71.057083,	42.361145]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"North Dartmouth","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-70.969455,	41.640396]}},
 {"type":"Feature","properties":{"code":11,"plant_name":"Salem","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-70.896713,	42.519539]}},  
{"type":"Feature","properties":{"code":11,"plant_name":"Mattapoisett","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Hydro":70}},"geometry":{"type":"Point","coordinates":[-70.815074,	41.661632]}},
{"type":"Feature","properties":{"code":7,"plant_name":"Portland","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-70.256819,	43.659099]}},
                                                     

{"type":"Feature","properties":{"code":7,"plant_name":"Red Wing","capacity_mw":"American Wrestling Association","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-92.536956,	44.566069]}},
                                                     
{"type":"Feature","properties":{"code":7,"plant_name":"River Falls","capacity_mw":"American Wrestling Association","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-92.623808,	44.861356]}},
                                                     
                                                     
{"type":"Feature","properties":{"code":7,"plant_name":"Rochester","capacity_mw":"American Wrestliong Association","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-92.480199,	44.0121229]}},
                                                     

{"type":"Feature","properties":{"code":7,"plant_name":"High Point","capacity_mw":"MId-Atlantic Championship Wrestling","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-79.997498,	35.970554]}},
                                                     
                                                     
{"type":"Feature","properties":{"code":7,"plant_name":"Pittsburgh","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-79.995888,	40.440624]}},
                                                     
                                                     
{"type":"Feature","properties":{"code":7,"plant_name":"West Palm Beach","capacity_mw":"Championship Wrestling from Florida","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-80.064163,	26.709723]}},
                                                     
{"type":"Feature","properties":{"code":7,"plant_name":"Charleston","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-79.940918,	32.784618]}},
                                                     
{"type":"Feature","properties":{"code":7,"plant_name":"Greensboro","capacity_mw":"Mid-Atlantic Championship Wrestling","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-79.766235,	36.044659]}},
                                                     
{"type":"Feature","properties":{"code":7,"plant_name":"Madison Square Garden","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-73.993439,	40.750505]}},
                                                     
{"type":"Feature","properties":{"code":7,"plant_name":"Kingston","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-73.997361,	41.927037]}},
                                                     
{"type":"Feature","properties":{"code":7,"plant_name":"Hackensack","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":130}},"geometry":{"type":"Point","coordinates":[-74.043474,	40.885933]}},

                                                     

                                                     
                                                     
                                                     
{"type":"Feature","properties":{"code":8,"plant_name":"Lewiston","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Coal":1241}},"geometry":{"type":"Point","coordinates":[-70.214776,	44.100351]}},{"type":"Feature","properties":{"code":9,"plant_name":"Bangor","capacity_mw":"World Wide Wrestling Federation","fuel_source":{"Natural Gas":62}},"geometry":{"type":"Point","coordinates":[-68.795013,	44.808147]}}]}

